esphome:
  name: skyscraper_irrigation

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Irrigation Fallback Hotspot"
    password: !secret wifi_ap_password_irrigation

switch:
  - platform: gpio
    pin: D7
    id: relay
    name: "Water valve relay"
    on_turn_on:
    - delay: 120s
    - switch.turn_off: relay

time:
  - platform: sntp
    on_time:
      - seconds: 0
        minutes: 30
        hours: 8
        then:
          - switch.toggle: relay

captive_portal:
    